/* ============================================================
   INVENTATORII — levels-fix.js
   LABORATORUL DE MISTERE · 100 de nivele
   Nu e de ajuns să ghicești explicația: aduni indicii,
   pui cauzele în ordine, alegi rezolvarea și demonstrezi
   că ai înțeles, pe o situație nouă.

   Format rând:
   [ scena, propsScena, titlu, poveste, indicii, lant, remediu, deCe, transfer? ]

   • indicii — 'icoana~text~1' (indiciu bun) sau '~0' (nu ajută), separate cu |
   • lant    — cauzele în ORDINEA corectă, separate cu | (se amestecă în joc)
   • remediu — 'întrebare|varianta A;varianta B;varianta C|indexCorect'
   • transfer— aceeași formă; verifică dacă ideea a fost înțeleasă, nu memorată
   ============================================================ */
window.LEVELS_FIX = {

  chapters: [
    { t: 'Mistere în bucătărie', d: 'Mâncare, apă și abur care se poartă ciudat.', dif: 1, ic: 'oala' },
    { t: 'Mistere prin casă', d: 'Uși, geamuri, becuri și baloane lipite.', dif: 1, ic: 'usa' },
    { t: 'Mistere în grădină', d: 'Plante, pietre și găleți crăpate.', dif: 1, ic: 'planta' },
    { t: 'Vremea năzdrăvană', d: 'Rouă, ceață, fulgere și zăpadă.', dif: 2, ic: 'nor' },
    { t: 'Mistere la școală', d: 'Cretă, caiete, laptopuri și ecou.', dif: 2, ic: 'carte' },
    { t: 'Animale și plante', d: 'De ce fac viețuitoarele ce fac.', dif: 2, ic: 'pasare' },
    { t: 'Apă, gheață și abur', d: 'Cele trei fețe ale apei.', dif: 2, ic: 'gheata' },
    { t: 'Lumină, umbre și sunet', d: 'Ce vede ochiul și ce aude urechea.', dif: 3, ic: 'prisma' },
    { t: 'Forțe și mișcare', d: 'Inerție, frecare, pârghii și echilibru.', dif: 3, ic: 'roata' },
    { t: 'Energie și electricitate', d: 'Curent, baterii, căldură și consum.', dif: 3, ic: 'baterie' }
  ],

  list: [
    /* ---------- 1. MISTERE ÎN BUCĂTĂRIE ---------- */
    ['bucatarie', 'pahar,soare', 'Paharul pe jumătate gol',
      'Ana a lăsat luni dimineața un pahar plin cu apă pe pervaz. Joi, apa ajungea doar până la jumătate. Nimeni nu a băut din el și paharul nu are nicio fisură.',
      'soare~Pervazul stă în soare toată ziua~1|pahar~Paharul nu are capac~1|ceas~Au trecut trei zile întregi~1|pisica~Pisica a dormit pe canapea~0|usa~Ușa camerei a fost închisă~0',
      'Soarele a încălzit apa din pahar|Picăturile de la suprafață au devenit vapori|Vaporii s-au amestecat în aerul camerei',
      'Ce faci ca apa să nu mai scadă?|Pui un capac pe pahar;Pui zahăr în apă;Muți paharul mai aproape de geam|0',
      'Apa nu a dispărut: s-a evaporat. La suprafață, cele mai iuți particule scapă în aer. Căldura și aerul care circulă grăbesc totul.',
      'Unde se evaporă apa cel mai repede?|Într-o farfurie lată, la soare;Într-o sticlă cu dop;Într-un pahar din frigider|0'],

    ['strada', 'foc,minge', 'Ciocolata din buzunar',
      'Rareș a pus un baton de ciocolată în buzunar și a plecat la fotbal. Când l-a scos, era o pungă moale, plină cu ciocolată curgătoare.',
      'foc~Afară au fost 30 de grade~1|minge~A alergat două ore în soare~1|ceas~Ciocolata a stat în buzunar tot timpul~1|gheata~Frigiderul de acasă merge bine~0|cana~Nu a băut nimic cald~0',
      'Soarele și corpul au încălzit buzunarul|Ciocolata a trecut de 32 de grade|Untul de cacao din ea s-a topit',
      'Cum duci ciocolata întreagă până acasă?|În ghiozdan, la umbră;În buzunarul de la pantaloni;Strânsă în mână|0',
      'Ciocolata se topește pe la 32–35 de grade, adică aproape la temperatura corpului. De aceea se topește în gură — dar și în buzunar.'],

    ['bucatarie', 'cutie,abur', 'Pâinea cu blăniță verde',
      'Pâinea caldă a fost pusă direct în punga de plastic și legată bine. După cinci zile, avea pete verzi-albăstrui.',
      'abur~Pâinea a fost pusă caldă în pungă~1|pahar~Punga era legată etanș~1|ceas~A stat așa cinci zile~1|pisica~Pisica a stat pe masă~0|soare~Afară a fost înnorat~0',
      'Aburul din pâinea caldă a rămas închis în pungă|Interiorul pungii a devenit cald și umed|Mucegaiul a găsit exact ce îi trebuie și a crescut',
      'Cum ții pâinea bună mai mult timp?|O lași să se răcească și o pui în hârtie;O legi caldă în plastic;O ții lângă aragaz|0',
      'Mucegaiul e o ciupercă, iar sporii lui plutesc peste tot în aer. Ca să crească are nevoie de trei lucruri: hrană, căldură și umezeală.'],

    ['bucatarie', 'cutie,planta', 'Bananele înnegrite',
      'Ana a pus bananele în fructieră, lângă mere. În patru zile s-au făcut negre, deși erau verzui la cumpărare.',
      'planta~Bananele au stat lipite de mere~1|cutie~Fructiera stă într-un colț cald~1|ceas~Au trecut patru zile~1|gheata~Frigiderul era gol~0|apa~Nu au fost udate~0',
      'Merele coapte au eliberat un gaz numit etilenă|Gazul a grăbit coacerea bananelor|Coaja lor s-a înmuiat și s-a înnegrit',
      'Cum păstrezi bananele galbene mai mult?|Le ții separat de mere;Le pui lângă mere;Le înfășori în folie, la cald|0',
      'Fructele coapte eliberează etilenă, un gaz care le spune celorlalte „grăbiți-vă". De aceea un singur măr copt poate strica tot coșul.'],

    ['bucatarie', 'sticla,masa', 'Laptele acru',
      'Sticla de lapte a rămas pe masă peste noapte. Dimineața mirosea acru și se făcuse ca o brânză moale.',
      'masa~Sticla a stat pe masă toată noaptea~1|foc~În bucătărie a fost cald~1|ceas~Au trecut 12 ore~1|gheata~Frigiderul funcționează bine~0|sare~Nimeni nu a pus nimic în lapte~0',
      'Laptele a stat multe ore la căldură|Bacteriile din el s-au înmulțit repede|Ele au produs acid, iar laptele s-a acrit',
      'Ce oprește acrirea?|Frigul din frigider;Un capac mai strâns;Agitarea sticlei|0',
      'Bacteriile se înmulțesc de câteva ori mai repede la 25 de grade decât la 4. Frigiderul nu le omoară: doar le încetinește foarte mult.'],

    ['bucatarie', 'pahar,gheata', 'Paharul care transpiră',
      'Rareș a pus limonadă cu gheață pe masă. După zece minute, paharul era ud pe dinafară, iar sub el se făcuse o baltă. Paharul nu are nicio crăpătură.',
      'gheata~În pahar sunt cuburi de gheață~1|abur~Afară e cald și umed~1|pahar~Sticla paharului e întreagă~1|pisica~Pisica a sărit pe masă~0|soare~Perdeaua e trasă~0',
      'Paharul rece a răcit aerul din jurul lui|Vaporii de apă din acel aer s-au răcit brusc|Ei s-au transformat în picături pe sticlă',
      'De unde vine apa de pe exteriorul paharului?|Din aerul din cameră;Din pahar, prin sticlă;De pe masă|0',
      'Aerul cald ține în el mulți vapori de apă. Când se răcește lângă pahar, nu îi mai poate ține și îi lasă să se adune: se numește condens.',
      'Când se aburesc mai tare ochelarii?|Când intri iarna din frig în casă;Vara, afară;Când bate vântul|0'],

    ['bucatarie', 'oala,foc', 'Oul crăpat',
      'Ana a luat un ou din frigider și l-a pus direct în apa care clocotea. După câteva secunde, din coajă a ieșit un fir alb.',
      'gheata~Oul venea direct din frigider~1|foc~Apa clocotea puternic~1|sare~În apă nu s-a pus sare~1|ceas~A fiert zece minute~0|pahar~Oala era curată~0',
      'Oul rece a intrat brusc în apă foarte fierbinte|Aerul și lichidul dinăuntru s-au dilatat rapid|Presiunea a crăpat coaja',
      'Cum fierbi ouăle fără să crape?|Le pui în apă rece și încălzești încet;Le arunci în apă clocotită;Dai focul la maximum|0',
      'Aproape tot se dilată când se încălzește. Dacă interiorul oului se dilată mai repede decât coaja, coaja cedează.'],

    ['bucatarie', 'sare,abur', 'Sarea împietrită',
      'Solnița stă pe raftul de lângă aragaz. De o săptămână, sarea nu mai curge: s-a făcut un bulgăre tare.',
      'abur~Lângă aragaz fierbe des apă~1|sare~Sarea trage apa din aer~1|pahar~Capacul solniței are găuri mari~1|pisica~Pisica nu ajunge acolo~0|ceas~E dimineață~0',
      'Aburul din bucătărie a intrat în solniță|Sarea a absorbit umezeala din aer|Bobițele s-au lipit între ele',
      'Unde e cel mai bun loc pentru solniță?|Într-un dulap uscat, departe de aragaz;Chiar lângă oala cu apă;Pe pervaz, la soare|0',
      'Sarea este higroscopică: atrage apa din aer. De aceea unii pun boabe de orez în solniță — ele absorb umezeala în locul sării.'],

    ['bucatarie', 'oala,foc', 'Aluatul care a crescut singur',
      'Bunica a acoperit vasul cu aluat și l-a lăsat lângă calorifer. După două ore, aluatul se umflase de două ori și dăduse pe deasupra.',
      'foc~Vasul a stat lângă calorifer~1|seminte~În aluat s-a pus drojdie~1|ceas~A stat acoperit două ore~1|gheata~Frigiderul era plin~0|apa~Nu s-a mai adăugat apă~0',
      'Drojdia a mâncat zahărul din aluat|Ea a produs bule de dioxid de carbon|Bulele prinse în cocă au umflat aluatul',
      'Unde crește aluatul cel mai repede?|La căldură, acoperit;În frigider;Afară, în curent|0',
      'Drojdia e o ciupercă vie. Se hrănește cu zahăr și scoate gaz. Miile de bule rămase în cocă fac pâinea pufoasă.'],

    ['bucatarie', 'cana,lingura', 'Lingurița fierbinte',
      'Rareș a pus lingurița de metal în ceaiul clocotit ca să amestece. Peste un minut, a atins mânerul și l-a lăsat repede: frigea.',
      'foc~Ceaiul era clocotit~1|lingura~Lingurița e de metal~1|ceas~A stat în ceașcă un minut~1|pahar~Ceașca e de porțelan~0|sare~Nu s-a pus zahăr~0',
      'Căldura ceaiului a intrat în capătul scufundat|Metalul a transmis căldura din aproape în aproape|Mânerul s-a încălzit și el',
      'Ce lingură nu se încinge așa tare?|Una de lemn;Una de metal subțire;Una de metal gros|0',
      'Metalele sunt bune conducătoare de căldură: o transmit repede prin toată bucata. Lemnul și plasticul o transmit foarte greu.',
      'De ce au oalele mânere de lemn sau plastic?|Ca să nu transmită căldura la mână;Ca să fie mai frumoase;Ca să fie mai grele|0'],

    /* ---------- 2. MISTERE PRIN CASĂ ---------- */
    ['camera', 'bec,intrerupator', 'Becul care nu se mai aprinde',
      'Becul din baie nu se aprinde. În restul casei e lumină, iar becul a fost cumpărat săptămâna trecută.',
      'intrerupator~Întrerupătorul face clic, fără efect~1|bec~Ieri becul a pâlpâit de câteva ori~1|fir~Becul din hol se aprinde normal~1|bec~Becul e înșurubat până la capăt~0|pisica~Pisica a dormit în baie~0',
      'Filamentul becului era deja slăbit, de aceea pâlpâia|La ultima apăsare s-a rupt complet|Circuitul s-a întrerupt și becul nu mai luminează',
      'Cum verifici cel mai simplu?|Pui becul din hol în locul lui;Schimbi întrerupătorul;Chemi imediat electricianul|0',
      'Când ceva nu merge, schimbă o singură piesă o dată. Dacă becul din hol se aprinde în baie, problema nu era la instalație.'],

    ['camera', 'usa,soare', 'Ușa care se blochează vara',
      'Iarna, ușa camerei se închidea perfect. Acum, în august, trebuie împinsă cu umărul și se freacă sus, în colț.',
      'soare~Afară e cald și umed de săptămâni~1|usa~Ușa e din lemn masiv~1|ceas~Iarna se închidea perfect~1|pisica~Pisica se sprijină de ușă~0|apa~Nu s-a vărsat apă pe ea~0',
      'Aerul umed de vară a pătruns în lemn|Lemnul a absorbit apa și s-a umflat|Ușa a devenit prea mare pentru tocul ei',
      'Ce ajută cel mai mult?|Un aparat care usucă aerul din cameră;Să tragi mai tare de ușă;Să uzi lemnul|0',
      'Lemnul respiră: absoarbe umezeala din aer și se umflă, apoi se usucă și se strânge la loc. De aceea ușile vechi merg altfel vara și iarna.'],

    ['camera', 'oglinda,abur', 'Oglinda care a dispărut',
      'După dușul fierbinte, oglinda din baie e complet albă. Nu se vede nimic în ea, iar pe margini s-au adunat picături.',
      'abur~Dușul a fost foarte fierbinte~1|oglinda~Sticla oglinzii e rece~1|usa~Ușa băii a fost închisă~1|ceas~Era seara~0|sare~Nimeni nu a spălat oglinda~0',
      'Apa fierbinte a umplut baia cu vapori|Vaporii au atins sticla rece a oglinzii|Ei s-au transformat în mii de picături fine',
      'Cum eviți aburirea?|Pornești ventilația sau deschizi ușa;Faci dușul mai fierbinte;Ștergi oglinda înainte|0',
      'E același fenomen ca la paharul cu gheață: vaporii calzi ating o suprafață rece și devin apă. Se numește condens.'],

    ['camera', 'fereastra,gheata', 'Geamul care plânge iarna',
      'Afară sunt −5 grade. Dimineața, pe partea dinăuntru a geamului sunt picături, iar pe pervaz o dâră de apă. Ferestrele sunt noi și bine închise.',
      'gheata~Afară sunt −5 grade~1|fereastra~Sticla e rece pe interior~1|oala~Seara s-a fiert supă mult timp~1|soare~E înnorat~0|usa~Ușa balconului e închisă~0',
      'Gătitul a umplut casa cu vapori de apă|Vaporii au ajuns la geamul rece|S-au condensat în picături pe partea dinăuntru',
      'Cum scapi de apa de pe geam?|Aerisești câteva minute după ce gătești;Ștergi geamul de trei ori pe zi;Pui un covor gros|0',
      'Apa nu vine de afară, ci chiar din casă: din gătit, din duș, din respirația ta. Aerisirea scurtă o scoate afară.',
      'Pe ce parte a geamului apar picăturile iarna?|Pe interior;Pe exterior;Pe amândouă la fel|0'],

    ['camera', 'planta,fereastra', 'Planta care se apleacă',
      'Ghiveciul cu mușcată stă pe biroul de lângă fereastră de o lună. Toate frunzele și tulpina s-au întors spre geam, iar planta arată strâmb.',
      'soare~Lumina intră doar dintr-o parte~1|planta~Planta nu a fost rotită niciodată~1|ghiveci~Ghiveciul stă în același loc de o lună~1|apa~A fost udată normal~0|pisica~Pisica nu a atins-o~0',
      'Lumina a venit mereu dintr-o singură parte|Celulele din partea umbrită s-au alungit mai mult|Tulpina s-a curbat spre fereastră',
      'Cum crește planta dreaptă?|O rotești puțin la câteva zile;O legi strâns de un băț;O uzi mai des|0',
      'Se numește fototropism. Partea aflată în umbră crește mai repede, iar planta se apleacă singură spre lumină.'],

    ['camera', 'telefon,baterie', 'Telecomanda mută',
      'Televizorul pornește de la butonul de pe el, dar telecomanda nu mai face nimic. Ieri, cineva a scos bateriile ca să le verifice.',
      'baterie~O baterie e pusă invers~1|baterie~Bateriile sunt de anul trecut~1|telefon~Televizorul pornește de la buton~1|pisica~Pisica a stat pe telecomandă~0|bec~Becul din cameră merge~0',
      'Bateriile au fost scoase și puse la loc greșit|Curentul nu a mai putut face un drum complet|Telecomanda nu a mai trimis niciun semnal',
      'Ce verifici primul?|Dacă bateriile sunt puse cu + și − corect;Dacă televizorul e stricat;Dacă ești prea departe|0',
      'Curentul circulă într-o singură direcție prin circuit. O baterie întoarsă e ca un pod ridicat: nu mai trece nimic.'],

    ['camera', 'usa,panza', 'Dulapul care miroase',
      'Hainele scoase din dulapul de pe peretele dinspre stradă miros a umezeală, deși au fost spălate. În colțul de sus al dulapului sunt pete cenușii.',
      'apa~Dulapul stă pe peretele exterior, rece~1|usa~Ușile stau mereu închise~1|panza~Hainele au fost puse ușor umede~1|soare~Camera e însorită~0|ceas~E toamnă~0',
      'Umezeala a rămas închisă în dulap|Aerul nu a circulat deloc|Au apărut mucegaiul și mirosul',
      'Ce rezolvă problema?|Aerisești dulapul și pui hainele bine uscate;Pui un parfum înăuntru;Închizi ușile mai bine|0',
      'Mirosul de „umed" este semnul mucegaiului. Fără aer și cu umezeală, el crește chiar și pe haine curate.'],

    ['camera', 'fereastra,soare', 'Praful din raza de soare',
      'Când soarele intră pe fereastră, se vede un roi de praf. Ana șterge zilnic, dar cel mai mult praf se adună tot lângă geam.',
      'fereastra~Fereastra se ține des deschisă~1|vant~Strada e la 20 de metri~1|soare~Raza de soare face praful vizibil~1|pisica~Pisica doarme în alt colț~0|carte~Rafturile sunt pline de cărți~0',
      'Aerul de afară a intrat pe fereastră|El a adus praf de pe stradă|Praful s-a așezat mai ales în apropierea geamului',
      'Cum reduci praful?|Pui o plasă fină și ștergi cu cârpă umedă;Ștergi doar cu cârpă uscată;Ții geamul mereu deschis|0',
      'Praful din rază a fost mereu acolo: lumina doar îl arată. Cârpa umedă îl prinde, cea uscată îl mută dintr-un loc în altul.'],

    ['camera', 'lemn,foc', 'Parchetul care scârțâie iarna',
      'Vara, podeaua e tăcută. Din decembrie, fiecare pas prin hol scârțâie, mai ales lângă calorifer.',
      'gheata~Afară e ger de câteva săptămâni~1|foc~Caloriferele merg la maximum~1|lemn~Podeaua e din scânduri de lemn~1|pisica~Pisica aleargă noaptea~0|usa~Ușa e nouă~0',
      'Aerul cald de iarnă e foarte uscat|Lemnul a pierdut apă și s-a strâns puțin|Scândurile au început să se frece între ele la fiecare pas',
      'Ce ar ajuta?|Un vas cu apă lângă calorifer, pentru umezeală;Să calci mai încet;Să dai căldura și mai tare|0',
      'Iarna, aerul din casă e mai uscat decât în deșert. Lemnul pierde apă, se strânge și apar jocuri între scânduri.'],

    ['camera', 'balon,fereastra', 'Balonul lipit de perete',
      'Ana a frecat balonul de păr și l-a pus pe perete. A rămas lipit acolo aproape zece minute, deși nu are lipici și nu e nimic magnetic în perete.',
      'balon~Balonul a fost frecat bine de păr~1|vant~Aerul din casă e uscat, e iarnă~1|ceas~S-a lipit imediat, fără lipici~1|apa~Peretele nu e ud~0|magnet~Nu există magnet în apropiere~0',
      'Frecarea a mutat sarcini electrice de pe păr pe balon|Balonul a rămas încărcat electric|El a atras peretele neutru și s-a lipit de el',
      'Cum se dezlipește balonul mai repede?|Îl atingi cu mâna udă;Îl freci și mai mult;Îl umfli mai tare|0',
      'Este electricitate statică: aceeași care îți ridică părul măciucă și îți dă scântei la clanță, iarna.',
      'Când apar mai multe scântei statice?|Iarna, când aerul e uscat;Vara, când e umed;Imediat după ploaie|0'],

    /* ---------- 3. MISTERE ÎN GRĂDINĂ ---------- */
    ['gradina', 'ghiveci,apa', 'Floarea udată prea mult',
      'Ana a udat mușcata în fiecare zi, uneori de două ori, „ca să fie sigură". Frunzele s-au îngălbenit și s-au lăsat moi, iar pământul e ud și greu.',
      'apa~Pământul e ud tot timpul~1|ghiveci~Ghiveciul nu are gaură de scurgere~1|tava~Farfuria de dedesubt e mereu plină~1|soare~Planta stă la lumină bună~0|seminte~A fost sănătoasă un an întreg~0',
      'Apa nu a avut pe unde să iasă din ghiveci|Rădăcinile au stat scufundate, fără aer|Ele au putrezit, iar planta s-a ofilit',
      'Ce faci?|Faci găuri în fund și uzi mai rar;Uzi și mai des;Muți planta la întuneric|0',
      'Rădăcinile au nevoie și de aer, nu doar de apă. Prea multă apă îneacă planta la fel de sigur cum o usucă seceta.'],

    ['gradina', 'carton,planta', 'Peticul galben de iarbă',
      'Sub covorul de joacă lăsat două săptămâni pe gazon, iarba a devenit galben-pai. În jur, iarba e verde și deasă.',
      'soare~Peticul a fost acoperit două săptămâni~1|carton~Covorul e gros și nu lasă lumina~1|planta~Iarba din jur e verde~1|apa~A plouat normal~0|furnica~Sunt furnici prin curte~0',
      'Covorul a oprit complet lumina|Iarba nu a mai putut face fotosinteză|Fără hrană, și-a pierdut culoarea verde',
      'Ce se întâmplă dacă ridici covorul acum?|Iarba redevine verde în câteva zile;Rămâne galbenă pentru totdeauna;Se usucă de tot|0',
      'Verdele vine de la clorofilă, care lucrează doar la lumină. Fără lumină, planta nu mai produce hrană și se decolorează.'],

    ['gradina', 'planta,ploaie', 'Roșiile crăpate',
      'După zece zile de secetă a plouat torențial o noapte întreagă. Dimineața, aproape toate roșiile aproape coapte aveau crăpături adânci.',
      'ploaie~A plouat mult și brusc~1|soare~Înainte fusese secetă zece zile~1|planta~Roșiile erau aproape coapte~1|furnica~Sunt furnici pe tulpină~0|vant~A bătut vântul~0',
      'După secetă, rădăcinile au tras deodată foarte multă apă|Miezul roșiei s-a umflat rapid|Coaja nu a mai ținut pasul și a plesnit',
      'Cum eviți crăpăturile?|Uzi puțin și des, constant;Uzi o dată pe săptămână, mult;Nu uzi deloc|0',
      'Coaja crește mai încet decât miezul. Când interiorul se umflă brusc, coaja se rupe — exact ca un balon umflat prea repede.'],

    ['gradina', 'copac,vant', 'Merele căzute prea devreme',
      'Merele erau încă mici și verzi. După o noapte cu vânt puternic, jumătate erau pe iarbă, cu codițele rupte.',
      'vant~A fost o noapte cu rafale puternice~1|copac~Pomul era foarte încărcat de fructe~1|planta~Crenguțele sunt subțiri~1|soare~A fost cald~0|apa~Pomul a fost udat~0',
      'Pomul avea prea multe fructe pe crengi subțiri|Vântul a legănat puternic crengile|Codițele slăbite s-au rupt și merele au căzut',
      'Cum protejezi recolta?|Rărești fructele și sprijini crengile;Uzi mult mai des;Culegi totul verde|0',
      'Un pom prea încărcat se rupe singur. De aceea grădinarii rup din fructe vara: cele rămase cresc mai mari și stau mai sigur.'],

    ['gradina', 'furnica,planta', 'Furnicile de pe trandafir',
      'Pe tulpina trandafirului urcă un șir nesfârșit de furnici. Frunzele sunt lipicioase, iar pe dosul lor sunt insecte verzi, minuscule.',
      'albina~Pe dosul frunzelor sunt insecte verzi~1|planta~Frunzele sunt lipicioase~1|furnica~Furnicile urcă mereu pe același drum~1|apa~Planta e udată normal~0|soare~Locul e însorit~0',
      'Păduchii de frunze au supt seva plantei|Ei au lăsat în urmă o substanță dulce și lipicioasă|Furnicile au venit la dulce și au rămas acolo',
      'Cum scapi de furnici?|Scapi întâi de păduchii de frunze;Uzi mai mult planta;Muți planta în casă|0',
      'Furnicile nu mănâncă planta: mănâncă „mierea" lăsată de păduchi. Uneori chiar îi apără de buburuze, ca pe niște vaci mici.'],

    ['gradina', 'seminte,rigla', 'Semințele care nu răsar',
      'Rareș a semănat ridichi acum trei săptămâni. Pământul e umed, locul e însorit, dar nu a ieșit niciun fir. Semințele îngropate le găsește, umflate și moi.',
      'seminte~Semințele au fost puse la 5 cm adâncime~1|rigla~Pe plic scria „se seamănă la 1 cm"~1|gheata~Nopțile au fost reci~1|apa~Pământul a fost udat~0|soare~Locul e însorit~0',
      'Semințele mici au fost îngropate mult prea adânc|Rezerva lor de hrană s-a terminat înainte de a ajunge la lumină|Firele au murit sub pământ',
      'La ce adâncime se pun semințele mici?|Cam de două ori grosimea lor;Cât mai adânc;Direct pe pământ, la vedere|0',
      'Sămânța are o rezervă mică de hrană, doar cât să ajungă la lumină. De acolo încolo se hrănește singură, prin frunze.'],

    ['gradina', 'gheata,rock', 'Zăpada topită lângă zid',
      'În mijlocul curții zăpada e întreagă, dar lângă zidul de cărămidă dinspre sud s-a topit o fâșie de jumătate de metru. Nimeni nu a curățat acolo.',
      'rock~Zidul e din cărămidă, orientat spre sud~1|soare~Soarele a bătut în zid toată ziua~1|gheata~În mijlocul curții zăpada a rămas~1|vant~A fost vânt slab~0|ceas~Suntem în februarie~0',
      'Zidul închis la culoare a absorbit lumina soarelui|El s-a încălzit și a rămas cald și după-amiaza|Căldura lui a topit zăpada din apropiere',
      'Unde se topește zăpada prima dată?|Lângă ziduri însorite și pe trotuare;În mijlocul gazonului;Sub copaci|0',
      'Suprafețele închise la culoare absorb lumina și o transformă în căldură. Zăpada albă o trimite în cea mai mare parte înapoi.'],

    ['gradina', 'planta,soare', 'Frunzele galbene de vară',
      'A fost o săptămână cu 35 de grade și fără ploaie. Frunzele de jos ale fasolei s-au îngălbenit și s-au uscat, cele de sus sunt încă verzi.',
      'soare~Au fost 35 de grade o săptămână~1|apa~Nu a plouat de 12 zile~1|planta~Frunzele de jos s-au uscat primele~1|furnica~Nu se văd insecte~0|ghiveci~Pământul e bun~0',
      'Planta a pierdut multă apă prin frunze|Rădăcinile nu au mai găsit apă în pământul uscat|Planta a sacrificat frunzele de jos ca să salveze vârful',
      'Când e cel mai bine să uzi vara?|Dimineața devreme sau seara;La prânz, în soare;Nu contează ora|0',
      'La prânz, o mare parte din apă se evaporă înainte să ajungă la rădăcini. Seara și dimineața, apa chiar intră în pământ.'],

    ['gradina', 'rock,luna', 'Piatra udă pe dedesubt',
      'De trei zile nu a plouat. Dimineața, Rareș a întors o piatră plată din grădină: deasupra era uscată, dar dedesubt era udă, iar pământul de sub ea, noroios.',
      'rock~Sub piatră e umed dimineața~1|gheata~Noaptea s-a răcit mult~1|ploaie~Nu a plouat de trei zile~1|soare~Deasupra piatra e uscată~1|pisica~Pisica doarme pe piatră~0',
      'Noaptea, pământul și piatra s-au răcit|Vaporii de apă din sol au urcat spre suprafață|Sub piatra rece ei s-au condensat în picături',
      'De unde vine apa de sub piatră?|Din vaporii din pământ, condensați;Din ploaia de acum o săptămână;Dintr-un izvor|0',
      'Piatra rece e o capcană de condens. Din același motiv se adună apă sub o folie întinsă pe pământ, chiar și fără ploaie.'],

    ['gradina', 'galeata,gheata', 'Găleata crăpată de ger',
      'Găleata cu apă a rămas afară peste noapte, la −8 grade. Dimineața era plină cu gheață și avea o crăpătură lungă, de sus până jos.',
      'gheata~Noaptea au fost −8 grade~1|galeata~Găleata era plină ochi~1|rock~Crăpătura merge de sus în jos~1|pisica~Pisica nu a atins-o~0|soare~Ziua fusese frumoasă~0',
      'Apa din găleată a înghețat|Gheața ocupă mai mult loc decât apa|Ea a împins pereții până i-a crăpat',
      'Cum eviți asta iarna?|Golești vasele sau le umpli doar pe jumătate;Le umpli și mai mult;Le pui doar capac|0',
      'Apa e ciudată: aproape tot ce îngheață se strânge, dar ea se dilată cu 9%. De aceea plutește gheața și de aceea crapă țevile.',
      'De ce plutește gheața pe apă?|E mai ușoară la același volum;Pentru că e rece;Pentru că e albă|0'],

    /* ---------- 4. VREMEA NĂZDRĂVANĂ ---------- */
    ['ploios', 'apa,soare', 'Băltoacele care rămân la umbră',
      'A plouat dimineața. La ora 3, băltoacele din partea însorită a curții dispăruseră, iar cele de la umbra gardului erau la fel de mari.',
      'soare~Jumătate din curte stă la umbră~1|apa~Băltoaca din soare a dispărut~1|ceas~Au trecut trei ore~1|vant~Vântul a bătut peste tot la fel~0|rock~Pământul e la fel peste tot~0',
      'Soarele a încălzit apa din băltoaca luminată|Evaporarea s-a accelerat foarte mult acolo|Băltoaca rece, de la umbră, s-a evaporat mult mai încet',
      'Unde se usucă rufele cel mai repede?|La soare și în bătaia vântului;La umbră, fără vânt;În casă, cu geamul închis|0',
      'Evaporarea depinde de trei lucruri: căldură, vânt și cât de uscat e aerul. La umbră lipsește chiar primul.'],

    ['gradina', 'planta,luna', 'Roua de dimineață',
      'La ora 6, iarba e udă leoarcă, deși nu a plouat deloc. Sub streașină, iarba e complet uscată.',
      'gheata~Noaptea s-a răcit mult~1|soare~Cerul a fost senin toată noaptea~1|ploaie~Nu a plouat deloc~1|planta~Iarba e udă la 6 dimineața~1|pisica~Pisica a dormit în casă~0',
      'Noaptea senină a lăsat pământul să se răcească puternic|Aerul de lângă iarbă s-a răcit și el|Vaporii din aer s-au condensat pe firele reci',
      'După ce noapte găsești cea mai multă rouă?|Senină și rece, fără vânt;Înnorată și caldă;Cu vânt puternic|0',
      'Roua nu cade din cer: se formează chiar pe iarbă, din vaporii aerului. Sub streașină, aerul cald al casei o împiedică.',
      'Ce se formează dacă temperatura scade sub zero?|Brumă;Rouă;Ceață|0'],

    ['rau', 'apa,nor', 'Ceața de pe lac',
      'La răsărit, deasupra lacului plutea un strat alb, gros de un metru. Pe câmpul din jur nu era nimic. La ora 9, ceața dispăruse.',
      'apa~Apa lacului e mai caldă decât aerul~1|gheata~Dimineața e rece~1|abur~Ceața stă doar deasupra apei~1|vant~Nu bate deloc vântul~1|peste~În lac sunt pești~0',
      'Apa caldă a lacului a eliberat vapori|Vaporii au intrat în aerul rece de deasupra|Ei s-au condensat în milioane de picături fine: ceață',
      'Când se ridică ceața?|Când soarele încălzește aerul;Când se răcește și mai mult;Când începe ploaia|0',
      'Ceața este un nor care atinge pământul. Aceleași picături mici, doar că printre ele treci cu bicicleta.'],

    ['ploios', 'nor,ploaie', 'Fulgerul și tunetul',
      'Ana a văzut fulgerul, a numărat „unu, doi, trei, patru, cinci, șase" și abia atunci a bubuit tunetul. Bunicul a spus imediat: „E încă departe."',
      'stea~Fulgerul s-a văzut instantaneu~1|toba~Tunetul a venit după 6 secunde~1|ploaie~Furtuna se apropie dinspre deal~1|vant~Bate vântul~0|ceas~Era ora 8 seara~0',
      'Fulgerul și tunetul se produc în același moment|Lumina ajunge la ochi aproape instantaneu|Sunetul merge mult mai încet și ajunge mai târziu',
      'La 6 secunde între fulger și tunet, furtuna e la…|Cam 2 kilometri;Cam 20 de metri;Cam 200 de kilometri|0',
      'Sunetul face un kilometru în cam 3 secunde. Împarte secundele la 3 și afli, în kilometri, cât e până la furtună.',
      'De ce vezi fulgerul înaintea tunetului?|Lumina e mult mai rapidă decât sunetul;Fulgerul e mai puternic;Fulgerul e mai aproape|0'],

    ['ploios', 'gheata,masinuta', 'Zăpada de pe acoperiș',
      'Pe drum a rămas doar zloată murdară, dar pe acoperișul casei e un strat gros de 20 de centimetri. Pe acoperișul vecinului, zăpada s-a topit aproape toată.',
      'masinuta~Pe drum trec mașini și s-a pus sare~1|foc~Podul casei noastre nu e încălzit~1|gheata~Pe acoperișul nostru sunt 20 cm~1|soare~E înnorat de trei zile~0|vant~Vântul e slab~0',
      'Pe drum, roțile și sarea au topit și împrăștiat zăpada|Acoperișul rece nu a primit nici sare, nici trafic|Acolo zăpada a rămas neatinsă',
      'Pe ce acoperiș se topește zăpada cel mai repede?|Pe cel al unei case care pierde căldură prin pod;Pe cel bine izolat;Pe cel din nord|0',
      'Zăpada e un test de izolație gratuit: dacă se topește repede pe acoperișul tău, casa ta încălzește cerul.'],

    ['ploios', 'ghiveci,vant', 'Doar ghivecele înalte',
      'După furtună, cele trei ghivece înalte și subțiri de pe balcon erau răsturnate. Cele scunde și late, aflate lângă ele, nu s-au clintit.',
      'vant~Au fost rafale de 60 km/h~1|ghiveci~Doar cele înalte s-au răsturnat~1|rock~Cele scunde erau grele la bază~1|ploaie~A plouat puțin~0|planta~Plantele sunt sănătoase~0',
      'Vântul a împins suprafața mare a ghivecelor înalte|Baza lor îngustă nu a putut ține|Ele s-au rotit peste margine și au căzut',
      'Cum stabilizezi un ghiveci înalt?|Pui pietre grele pe fundul lui;Îl faci și mai înalt;Îl uzi mai mult|0',
      'Stabilitatea înseamnă bază largă și greutate cât mai jos. La fel sunt gândite camioanele, farurile și turnul tău de cuburi.'],

    ['munte', 'gheata,soare', 'Frigul de sus',
      'În vale erau 25 de grade și toată lumea în tricou. Sus, la 2000 de metri, termometrul arăta 5 grade, deși soarele era mai puternic ca oricând.',
      'termometru~La 2000 m erau doar 5 grade~1|soare~În vale erau 25 de grade~1|vant~Aerul de sus e mai rarefiat~1|gheata~Era plină vară~0|apa~Nu era zăpadă~0',
      'Aerul de sus e mai rar și apasă mai puțin|Aerul care urcă se destinde și se răcește|La fiecare kilometru urcat, temperatura scade cam 6 grade',
      'Ce iei în rucsac la o urcare de 1500 m?|O geacă, chiar dacă jos e cald;Doar tricou;Sandale|0',
      'Deși ești mai aproape de Soare, aerul de sus e prea subțire ca să țină căldura. Contează aerul, nu distanța.',
      'Cu cât scade temperatura la fiecare 1000 m urcați?|Cam 6 grade;Cu 30 de grade;Deloc|0'],

    ['strada', 'sare,gheata', 'Sarea de pe alee',
      'Aleea era o oglindă de gheață. Vecinul a împrăștiat sare și, în 20 de minute, gheața s-a transformat în apă — deși termometrul arăta tot −3 grade.',
      'sare~S-a împrăștiat sare pe toată aleea~1|gheata~Gheața s-a topit în 20 de minute~1|termometru~Afară sunt −3 grade~1|soare~Cerul e complet înnorat~1|pisica~Pisica a stat în casă~0',
      'Sarea s-a amestecat cu pelicula subțire de apă de pe gheață|Apa sărată îngheață abia sub zero grade|Gheața nu a mai putut rămâne solidă și s-a topit',
      'Când NU mai ajută sarea?|Când e mai frig de −15 grade;Când plouă;Când e soare|0',
      'Sarea coboară temperatura la care apa îngheață. La ger foarte mare nu mai e suficientă și se folosesc alte substanțe.'],

    ['ploios', 'ploaie,prisma', 'Curcubeul de după ploaie',
      'Ploaia a stat, soarele a ieșit și pe cer a apărut un curcubeu uriaș. Rareș a observat că îl vede doar dacă stă într-un anumit fel.',
      'ploaie~Tocmai a stat ploaia~1|soare~Soarele e jos, în spatele tău~1|apa~În aer sunt încă picături~1|vant~Bate vânt slab~0|nor~Cerul e parțial înnorat~0',
      'Lumina soarelui a intrat în picăturile de apă|În fiecare picătură s-a despărțit în culori|Culorile s-au întors, sub același unghi, spre ochiul tău',
      'Unde trebuie să fie Soarele ca să vezi curcubeul?|În spatele tău;Fix în fața ta;Exact deasupra ta|0',
      'Fiecare picătură e o prismă mică. Vezi curcubeul doar cu spatele la Soare și cu fața spre perdeaua de ploaie.',
      'Cum sunt culorile curcubeului?|În ordine, de la roșu la violet;Amestecate la întâmplare;Doar trei|0'],

    ['ploios', 'panza,vant', 'Rufele uscate de vânt',
      'Ziua a fost înnorată, dar cu vânt puternic. Rufele întinse desfăcute s-au uscat în trei ore, în timp ce prosopul lăsat îndoit era încă ud seara.',
      'vant~A bătut vântul toată ziua~1|panza~Rufele au fost întinse desfăcute~1|apa~Rufele au fost bine stoarse~1|soare~A fost înnorat~0|ceas~Au stat trei ore~0',
      'Apa de pe rufe s-a evaporat|Vântul a luat imediat vaporii de lângă țesătură|Aerul uscat venit în loc a preluat alți vapori, la nesfârșit',
      'Cum usuci rufele cel mai repede?|Desfăcute, în curent de aer;Îngrămădite la soare;Împăturite pe sârmă|0',
      'Fără vânt, aerul de lângă rufe se umple de vapori și evaporarea aproape se oprește. Vântul aduce mereu aer „gol".'],

    /* ---------- 5. MISTERE LA ȘCOALĂ ---------- */
    ['scoala', 'carte,burete', 'Creta care nu scrie',
      'Doamna a șters tabla cu buretele ud și a început imediat să scrie. Creta aluneca și lăsa doar o dâră cenușie, apoi s-a rupt.',
      'apa~Tabla a fost ștearsă cu buretele ud~1|burete~Buretele picura de apă~1|ceas~Nu s-a așteptat deloc să se usuce~1|carte~Creta e nouă~0|soare~În clasă e cald~0',
      'Pe tablă a rămas o peliculă de apă|Praful de cretă s-a amestecat cu apa|A rezultat o pastă care alunecă în loc să lase urmă',
      'Ce faci ca să scrii imediat?|Ștergi cu o cârpă uscată sau aștepți două minute;Apeși mult mai tare;Iei altă cretă|0',
      'Creta scrie pentru că se sfărâmă în praf, iar praful se agață de asperitățile tablei. Apa lipește praful și îl face noroi.'],

    ['scoala', 'carte,apa', 'Cerneala întinsă',
      'O picătură de apă a rămas pe bancă. Rareș a pus caietul peste ea și, când l-a ridicat, cuvintele scrise cu stiloul se transformaseră în pete albastre, ca niște rădăcini.',
      'apa~Pe bancă era o picătură de apă~1|carte~Foaia a stat direct peste picătură~1|rigla~Hârtia e făcută din fibre~1|soare~Nu bătea soarele~0|pisica~Nicio pisică prin clasă~0',
      'Apa a intrat între fibrele hârtiei|Fibrele au tras apa în toate direcțiile|Cerneala a călătorit odată cu apa și litera s-a transformat în pată',
      'Cum salvezi o pagină udă?|O usuci întinsă, cu hârtie absorbantă deasupra;O freci cu guma;O mototolești și o pui la calorifer|0',
      'Hârtia e o rețea de fibre cu mii de canale minuscule. Apa urcă prin ele — exact ca prin sfoara udătorului de flori.'],

    ['scoala', 'lipici,vant', 'Lipiciul pietrificat',
      'Vineri, lipiciul a rămas pe bancă, cu capacul alături. Luni, bățul era tare ca o cretă și nu mai lipea nimic.',
      'usa~Capacul a rămas deschis tot weekendul~1|vant~Fereastra clasei a fost lăsată întredeschisă~1|ceas~Au trecut trei zile~1|apa~Nu s-a vărsat nimic pe el~0|foc~Caloriferul e oprit~0',
      'Lichidul din compoziția lipiciului s-a evaporat în aer|A rămas doar partea solidă|Bățul s-a întărit și nu mai lipește',
      'Cum ții lipiciul bun?|Închizi capacul de fiecare dată;Îl ții deschis, la frigider;Îl uzi din când în când|0',
      'Multe lipiciuri sunt o pulbere ținută moale de un lichid. Când lichidul pleacă, rămâne doar praful întărit.'],

    ['scoala', 'sticla,carte', 'Ghiozdanul ud pe dinăuntru',
      'Afară nu a plouat deloc, dar cărțile din mijlocul ghiozdanului sunt ude, iar caietul de matematică s-a ondulat.',
      'sticla~Capacul sticlei de apă era slăbit~1|carte~Cărțile din mijloc sunt cele mai ude~1|ploaie~Afară nu a plouat deloc~1|pisica~Nicio pisică prin apropiere~0|cana~Nimeni nu a băut suc~0',
      'Capacul sticlei nu a fost strâns bine|Ghiozdanul s-a înclinat în bancă|Apa a curs din sticlă direct peste cărți',
      'Cum eviți dezastrul?|Ții sticla dreaptă, într-un buzunar separat;O pui culcată peste cărți;O ții tot timpul în mână|0',
      'Când cauți vinovatul, întreabă „de unde ar fi putut veni apa?". Dacă afară e uscat, sursa e sigur înăuntru.'],

    ['scoala', 'foc,carte', 'Guma care murdărește',
      'Guma lui Rareș a stat o săptămână pe calorifer. Acum, în loc să șteargă, lasă dâre cenușii și lipicioase pe caiet.',
      'foc~Guma a stat pe calorifer~1|soare~În clasă e foarte cald~1|carte~Urmele rămase sunt lipicioase~1|apa~Nu s-a udat~0|rigla~Rigla e curată~0',
      'Căldura a înmuiat cauciucul din gumă|Guma a devenit lipicioasă|La ștergere, a lăsat urme în loc să le ridice',
      'Unde ții guma?|În penar, departe de calorifer;Pe calorifer, să fie caldă;În buzunar, lipită de corp|0',
      'Guma șterge pentru că praful de creion se lipește de ea. Dacă se înmoaie prea tare, se lipește ea de hârtie.'],

    ['scoala', 'ceas,baterie', 'Ceasul din clasă rămâne în urmă',
      'Ceasul de perete merge, dar în fiecare zi rămâne cu circa 10 minute în urmă. Săptămâna trecută rămânea doar cu două.',
      'baterie~Bateria e pusă de trei ani~1|ceas~Rămâne tot mai mult în urmă~1|ceas~Acele se mișcă, dar încet~1|soare~Camera e normală~0|fir~Nu e conectat la priză~0',
      'Bateria s-a descărcat aproape complet|Mecanismul primește prea puțină energie|Acele se mișcă mai încet decât ar trebui',
      'Ce faci?|Schimbi bateria;Împingi acele înainte în fiecare zi;Îl scuturi bine|0',
      'Un aparat care merge „încet" e de multe ori un aparat înfometat de energie, nu unul stricat.'],

    ['scoala', 'telefon,foc', 'Laptopul care se oprește singur',
      'În timpul prezentării, laptopul a devenit fierbinte, ventilatorul a urlat câteva minute, apoi s-a stins brusc. Era în priză și avea 100% baterie.',
      'foc~E fierbinte sub tastatură~1|ventilator~Ventilatorul se aude foarte tare~1|panza~A stat pe pătură, pe pat~1|baterie~Era în priză, cu 100%~0|ceas~Mergea de două ore~0',
      'Pătura a astupat orificiile de aerisire|Aerul cald nu a mai avut pe unde să iasă|Laptopul s-a supraîncălzit și s-a oprit ca să se protejeze',
      'Pe ce pui laptopul?|Pe o suprafață tare și plată;Pe pernă;Sub pilotă|0',
      'Aparatele electronice produc căldură și au nevoie de aer care circulă. Oprirea bruscă e o protecție, nu o defecțiune.',
      'De ce are laptopul ventilator?|Ca să scoată aerul cald afară;Ca să facă zgomot;Ca să răcească camera|0'],

    ['scoala', 'balon,gheata', 'Balonul micșorat',
      'Balonul umflat în clasă a fost dus afară, la −5 grade. În zece minute părea pe jumătate dezumflat, deși nu are nicio gaură.',
      'gheata~Afară sunt −5 grade~1|balon~Balonul a fost umflat în clasa caldă~1|ceas~S-a micșorat în zece minute~1|apa~Nu are nicio gaură~1|soare~Nu bate soarele~0',
      'Aerul dinăuntru s-a răcit|Particulele reci se mișcă mai încet și se strâng|Balonul s-a micșorat, deși aerul a rămas tot acolo',
      'Ce se întâmplă dacă îl aduci înapoi în clasă?|Se umflă la loc;Rămâne mic pentru totdeauna;Se sparge|0',
      'Aerul cald ocupă mai mult loc decât aerul rece. De aceea zboară baloanele cu aer cald și de aceea scad roțile iarna.',
      'De ce scade presiunea în anvelope iarna?|Aerul rece ocupă mai puțin loc;Iese pe la valve;Cauciucul crește|0'],

    ['scoala', 'carte,apa', 'Toate culorile au dat maro',
      'Ana a pictat un apus. A folosit galben, roșu, albastru și verde, dar totul a ieșit maro-cenușiu, ca noroiul.',
      'carte~S-au amestecat toate culorile pe foaie~1|apa~Apa din borcan e tulbure~1|rigla~Pensula nu a fost clătită între culori~1|soare~Lumina din clasă e bună~0|ceas~A lucrat o oră~0',
      'Pensula nespălată a dus culoare veche în cea nouă|S-au amestecat culori opuse|Amestecul tuturor culorilor dă maro-cenușiu',
      'Cum păstrezi culorile curate?|Clătești pensula între culori;Amesteci mai repede;Pui mult mai multă apă|0',
      'Fiecare culoare oprește o parte din lumină. Amestecate toate, opresc aproape tot ce vine: rămâne un maro închis.'],

    ['scoala', 'minge,toba', 'Ecoul din sala de sport',
      'În sala goală, fiecare cuvânt se aude de două ori și nimeni nu înțelege ce strigă profesorul. Când sala e plină de copii, ecoul aproape dispare.',
      'minge~Sala e mare și goală~1|rock~Pereții sunt tari și netezi~1|panza~Nu există perdele sau saltele pe pereți~1|difuzor~Muzica nu e pornită~0|ceas~E ora de sport~0',
      'Sunetul a plecat de la vorbitor și a lovit peretele|Peretele tare l-a trimis înapoi|L-ai auzit a doua oară, cu o mică întârziere',
      'Ce reduce ecoul?|Perdele, saltele și panouri moi;Pereți și mai netezi;O sală mai mare|0',
      'Materialele moi absorb sunetul, cele tari îl reflectă. De aceea studiourile au pereți pufoși, iar sălile goale bubuie.']
,

    /* ---------- 6. ANIMALE ȘI PLANTE ---------- */
    ['laborator', 'peste,apa', 'Peștii care stau la suprafață',
      'De două zile, toți peștii din acvariu stau lipiți de suprafață și par că înghit aer. Apa e limpede, iar hrana a fost aceeași ca întotdeauna.',
      'peste~Peștii stau la suprafață și înghit aer~1|foc~Apa are 28 de grade, e caniculă~1|pompa~Pompa de aer e oprită de două zile~1|apa~Apa e limpede~0|seminte~Au fost hrăniți normal~0',
      'Apa caldă poate ține mai puțin oxigen|Fără pompă, oxigenul consumat nu s-a reînnoit|Peștii au urcat acolo unde apa atinge aerul',
      'Ce faci primul?|Pornești pompa și răcorești puțin apa;Le dai mai multă mâncare;Schimbi tot acvariul|0',
      'Oxigenul se dizolvă în apă, iar apa caldă ține mai puțin. De aceea, vara, peștii din bălțile mici suferă cel mai tare.'],

    ['camera', 'pisica,foc', 'Pisica de pe calorifer',
      'Iarna, pisica doarme pe calorifer. Vara, se mută în pata de soare de pe covor. În cameră sunt 21 de grade, exact cât le place oamenilor.',
      'pisica~Doarme mereu în locul cel mai cald~1|foc~Se mută pe calorifer seara~1|termometru~Camera are 21 de grade~1|apa~Are apă proaspătă~0|ceas~Doarme 16 ore pe zi~0',
      'Pisica are temperatura corpului mai mare decât a noastră|Ca să se încălzească singură ar consuma energie|Alege locul cald și economisește hrană',
      'Ce înseamnă acest obicei?|Că economisește energie, e perfect normal;Că e bolnavă;Că îi e foame|0',
      'Pisicile se simt bine la 30–36 de grade. Pentru ele, camera noastră e răcoroasă tot anul, chiar și vara.'],

    ['ferma', 'caine,soare', 'Câinele care gâfâie',
      'Sunt 32 de grade. Rex stă la umbră, nemișcat de o oră, dar gâfâie fără oprire, cu limba scoasă. Blana lui nu e udă nicăieri.',
      'caine~Gâfâie cu limba scoasă~1|soare~Sunt 32 de grade~1|panza~Are blană groasă și nu transpiră prin piele~1|apa~Bea foarte multă apă~1|minge~Nu a alergat de o oră~0',
      'Câinele aproape că nu transpiră prin piele|Singura lui răcire eficientă e prin respirație|Gâfâitul evaporă apă de pe limbă și îl răcorește',
      'Cum ajuți un câine pe caniculă?|Umbră, apă rece și plimbări seara;Îl tunzi până la piele;Îl lași în mașină, la umbră|0',
      'Evaporarea răcorește: la om prin transpirație, la câine prin limbă. Același truc al naturii, alt organ.',
      'De ce ți-e frig când ieși ud din apă?|Apa care se evaporă îți ia căldura;Pentru că apa e rece;Pentru că vântul e cald|0'],

    ['gradina', 'furnica,seminte', 'Șirul de furnici',
      'De la crăpătura din trotuar până la firimitura de biscuit e un șir perfect de furnici. Merg exact pe aceeași linie, deși ocolesc inutil o piatră.',
      'furnica~Merg exact pe aceeași linie~1|seminte~La capătul drumului e o firimitură~1|furnica~Cele care se întorc ating antenele cu cele care vin~1|apa~Traseul trece pe lângă o baltă~0|soare~E dimineață~0',
      'O furnică cercetașă a găsit mâncarea|Pe drumul de întoarcere a lăsat o urmă de miros|Celelalte au urmat urma și au întărit-o de fiecare dată',
      'Cum le rupi drumul?|Ștergi traseul cu o cârpă umedă și strângi firimiturile;Le sperii cu mâna;Muți firimitura cu 5 cm|0',
      'Feromonii sunt mesaje chimice. Un drum bun miroase tot mai puternic, pentru că fiecare furnică adaugă din al ei.'],

    ['padure', 'pasare,copac', 'Berzele au plecat',
      'În septembrie, cuibul de pe stâlp s-a golit. Vrăbiile și ciorile au rămas în sat, deși iarna e la fel de grea pentru toate păsările.',
      'pasare~Berzele au plecat în septembrie~1|albina~Insectele și broaștele au dispărut~1|gheata~Se apropie frigul~1|copac~Frunzele cad~0|ploaie~A plouat mult~0',
      'Toamna, insectele și broaștele dispar|Berzele, care se hrănesc cu ele, rămân fără mâncare|Ele zboară spre țările calde, unde hrana există tot anul',
      'De ce pleacă păsările călătoare?|Mai ales pentru hrană, nu doar de frig;Pentru că le e urât;Din cauza vântului|0',
      'Vrabia rămâne, barza pleacă. Diferența nu e blana, ci meniul: cine mănâncă semințe rezistă, cine mănâncă insecte pleacă.'],

    ['ploios', 'ploaie,planta', 'Râmele de pe trotuar',
      'După o noapte de ploaie, trotuarul e plin de râme. Unele se târăsc, altele s-au uscat deja la soare. Pe iarbă nu se vede niciuna.',
      'ploaie~A plouat toată noaptea~1|apa~Pământul e îmbibat cu apă~1|furnica~Râmele au ieșit tocmai pe trotuar~1|soare~Dimineața e răcoroasă~0|planta~Iarba e verde~0',
      'Apa a umplut toate galeriile din pământ|Aerul din ele a fost înlocuit de apă|Râmele au ieșit la suprafață ca să poată respira',
      'Ce e cel mai bine să faci?|Le muți pe pământ, la umbră;Le lași pe asfalt;Le pui într-un pahar cu apă|0',
      'Râmele respiră prin piele, care trebuie să rămână umedă. În apă multă se sufocă, iar pe asfaltul însorit se usucă.'],

    ['gradina', 'planta,lupa', 'Petele arse de pe frunze',
      'Ana a stropit frunzele plantelor la prânz, în plin soare. A doua zi, pe fiecare frunză erau pete albe, exact acolo unde stătuseră picăturile.',
      'apa~Planta a fost stropită la prânz~1|soare~Soarele bătea puternic~1|lupa~Petele sunt fix unde erau picăturile~1|furnica~Nu se văd insecte~0|ghiveci~Pământul e bun~0',
      'Picăturile au rămas pe frunze, în plin soare|Fiecare picătură bombată a concentrat lumina, ca o lupă|Sub ea, țesutul frunzei s-a ars',
      'Când stropești frunzele?|Dimineața devreme sau seara;Fix la prânz;Doar în soare puternic|0',
      'O picătură bombată e o lentilă adevărată. Ea adună razele într-un punct mic și îl încălzește mult mai tare decât restul frunzei.'],

    ['padure', 'gheata,copac', 'Ursul care doarme iarna',
      'Toamna, ursul a mâncat aproape fără oprire și s-a îngrășat mult. Din decembrie nu a mai ieșit din bârlog și nu a mâncat nimic până în martie.',
      'gheata~Iarna e ger lung~1|seminte~Fructele și insectele dispar complet~1|caine~Ursul s-a îngrășat mult toamna~1|apa~Râul a înghețat~0|ceas~E decembrie~0',
      'Iarna nu mai există destulă hrană în pădure|Ursul a strâns toamna o rezervă de grăsime|Corpul lui încetinește și trăiește din rezerve până primăvara',
      'Ce este hibernarea?|O încetinire a corpului, ca să consume foarte puțin;Un somn obișnuit, doar mai lung;O boală de iarnă|0',
      'În hibernare, inima ursului poate bate de câteva ori pe minut. Grăsimea arde încet, ca o lumânare ținută să nu se stingă.'],

    ['bucatarie', 'albina,planta', 'Muștele de la fructieră',
      'În jurul fructierei zboară muște mici, apărute de nicăieri. Nimeni nu a vărsat suc, iar bucătăria e curată. În mijlocul fructierei stă o banană foarte trecută.',
      'planta~O banană e trecută și moale~1|albina~Muștele zboară doar în jurul fructierei~1|cutie~Fructiera nu e acoperită~1|soare~În bucătărie e cald~1|apa~Nu s-a vărsat suc~0',
      'Fructul trecut a început să fermenteze|Mirosul dulce-acrișor s-a răspândit prin aer|Muștele de oțet l-au urmat până la sursă',
      'Cum scapi de ele?|Scoți fructul stricat și acoperi fructiera;Le alungi cu mâna;Adaugi și mai multe fructe|0',
      'Muștele de oțet simt mirosul fermentației de la zeci de metri. Fără sursă, în câteva zile dispar singure.'],

    ['padure', 'copac,planta', 'Iarba rară de sub copac',
      'Sub nucul bătrân, iarba e rară și firavă, deși e udată la fel ca restul curții. La doi metri distanță, gazonul e des și verde.',
      'copac~Coroana nucului e foarte deasă~1|soare~Sub copac e umbră toată ziua~1|apa~Rădăcinile copacului iau apa din sol~1|furnica~Sunt furnici prin iarbă~0|rock~Pământul nu e pietros~0',
      'Copacul oprește aproape toată lumina|Rădăcinile lui iau apa și hrana din sol|Iarba primește prea puțin din toate și crește rar',
      'Ce plantezi sub un copac des?|Plante care suportă umbra;Gazon obișnuit;Plante iubitoare de soare|0',
      'În natură, plantele concurează pentru lumină, apă și hrană. De obicei, cea mai mare și mai veche câștigă.'],

    /* ---------- 7. APĂ, GHEAȚĂ ȘI ABUR ---------- */
    ['munte', 'panza,gheata', 'Rufele înghețate care s-au uscat',
      'Bunica a întins rufele afară la −6 grade. Au înghețat imediat, țepene ca scândura. Seara erau uscate, deși nu s-au dezghețat niciun moment.',
      'gheata~Afară erau −6 grade~1|panza~Rufele erau țepene ca scândura~1|soare~Cerul senin, aerul foarte uscat~1|ceas~După șase ore erau uscate~1|ploaie~Nu a nins deloc~0',
      'Apa din rufe a înghețat imediat|Gheața a trecut direct în vapori, fără să se topească|Rufele s-au uscat, rămânând tot timpul reci',
      'Cum se numește trecerea directă din gheață în vapori?|Sublimare;Topire;Fierbere|0',
      'Da, se poate usca și înghețat. Din același motiv scade zăpada din curte în zilele geroase și însorite, fără să facă băltoace.'],

    ['bucatarie', 'oala,abur', 'Capacul care sare',
      'Apa fierbe în oală. Capacul, așezat drept, începe să se ridice singur și să zăngăne, iar pe margini iese abur cu putere.',
      'foc~Apa fierbe în clocot~1|abur~Din oală iese abur cu putere~1|capac~Capacul e așezat drept, fără fantă~1|sare~S-a pus sare în apă~0|ceas~Fierbe de cinci minute~0',
      'Apa fierbinte s-a transformat în abur|Aburul ocupă de peste o mie de ori mai mult loc decât apa|Presiunea crescută a ridicat capacul',
      'Cum eviți să dea în foc?|Dai focul mai mic și lași capacul întredeschis;Apeși capacul mai tare;Mărești focul|0',
      'Un pahar de apă devine, sub formă de abur, cât o cadă întreagă. De aceea aburul a putut mișca locomotive.',
      'Ce ocupă cel mai mult loc?|Aburul;Apa lichidă;Gheața|0'],

    ['bucatarie', 'sticla,gheata', 'Sticla spartă în congelator',
      'Rareș a pus o sticlă plină ochi cu apă în congelator, ca să o răcească repede, și a uitat-o. După trei ore, sticla era crăpată de sus până jos.',
      'gheata~Sticla a stat trei ore în congelator~1|sticla~Era plină ochi, cu dopul pus~1|apa~Apa dinăuntru a înghețat toată~1|sare~Nu s-a pus sare~0|ceas~Era seara~0',
      'Apa s-a răcit sub zero grade|La îngheț, ea s-a dilatat|Neavând unde să se ducă, a spart sticla',
      'Cum răcești o sticlă repede și în siguranță?|O scoți înainte de îngheț sau lași loc gol;O umpli complet;O uiți acolo peste noapte|0',
      'În gheață, particulele de apă se așază într-o rețea cu goluri. Rețeaua ocupă mai mult loc decât apa dezordonată.'],

    ['bucatarie', 'oala,abur', 'Aburul care apare la distanță',
      'Din ceainicul care fierbe, chiar la gura lui, nu se vede nimic. La doi centimetri mai încolo apare norul alb, care apoi dispare din nou.',
      'abur~Chiar la gura ceainicului nu se vede nimic~1|oala~Norul alb apare la doi centimetri~1|foc~Apa clocotește~1|pahar~Ceainicul e curat~0|vant~Nu e curent în bucătărie~0',
      'Din ceainic iese vapor de apă adevărat, care e invizibil|La câțiva centimetri, el se răcește în aerul din cameră|Se condensează în picături foarte mici — abia acelea se văd',
      'Ce este „aburul" alb pe care îl vezi?|Picături foarte mici de apă;Vapori invizibili;Fum|0',
      'Vaporii de apă sunt transparenți, ca aerul. Norul alb pe care îl numim abur este, de fapt, apă deja condensată.'],

    ['bucatarie', 'cana,lingura', 'Zahărul dispărut',
      'Ana a pus două lingurițe de zahăr în ceaiul fierbinte și a amestecat. Bobițele au dispărut complet, dar ceaiul e clar mai dulce.',
      'sare~Zahărul a fost pus în ceai fierbinte~1|lingura~S-a amestecat zece secunde~1|pahar~Ceaiul e vizibil mai dulce~1|apa~Nivelul lichidului e aproape la fel~0|ceas~Nu a trecut mult timp~0',
      'Bobițele de zahăr s-au desfăcut în particule minuscule|Ele s-au strecurat printre particulele de apă|Zahărul a rămas în ceai, dar nu se mai vede',
      'Unde s-a dus zahărul?|S-a dizolvat, e încă în ceai;S-a evaporat;S-a transformat în apă|0',
      'Dizolvarea nu e dispariție: gustul dovedește că zahărul e acolo. Dacă lași ceaiul să se evapore, zahărul rămâne pe fundul cănii.',
      'În ce se dizolvă zahărul cel mai repede?|În apă caldă, amestecată;În apă rece;În ulei|0'],

    ['bucatarie', 'pahar,apa', 'Uleiul care nu se amestecă',
      'Rareș a turnat ulei peste apă și a agitat puternic. Totul s-a amestecat, dar după un minut uleiul era din nou deasupra, într-un strat curat.',
      'pahar~Uleiul a revenit deasupra~1|apa~S-au amestecat la agitare, apoi s-au separat~1|cantar~Uleiul e mai ușor la același volum~1|sare~Nu s-a pus sare~0|foc~Nu s-a încălzit nimic~0',
      'Uleiul e mai puțin dens decât apa|Particulele lui nu se leagă de cele de apă|El urcă și formează un strat separat, deasupra',
      'Cum cureți o pată de ulei?|Cu detergent, care leagă uleiul de apă;Doar cu apă rece;Doar cu apă caldă|0',
      'Detergentul are un capăt care iubește apa și unul care iubește uleiul. El face legătura pe care apa singură nu o poate face.'],

    ['rau', 'sticla,barca', 'Sticla care plutește și se scufundă',
      'Sticla goală, cu dopul pus, plutește pe apă ca o barcă. Aceeași sticlă, umplută cu apă, se duce direct la fund.',
      'sticla~Goală și cu dop, plutește~1|apa~Plină cu apă, se scufundă~1|cantar~Aerul e mult mai ușor decât apa~1|pahar~Sticla e exact aceeași~0|sare~Apa e dulce~0',
      'Sticla goală conține aer, foarte ușor|Împreună, sticla și aerul cântăresc mai puțin decât apa dată la o parte|Plină cu apă, devine mai grea decât apa dată la o parte și se scufundă',
      'De ce plutește o navă de metal?|Pentru că înăuntru are foarte mult aer;Pentru că metalul plutește;Pentru că e vopsită|0',
      'Nu contează din ce e făcut obiectul, ci cât cântărește față de apa pe care o împinge la o parte. Aceasta e legea lui Arhimede.',
      'Ce plutește mai bine?|Un obiect cu mult aer înăuntru;Unul plin cu apă;Unul plin cu nisip|0'],

    ['camera', 'panza,vant', 'Prosopul îndoit care rămâne ud',
      'Două prosoape la fel de ude au stat în aceeași cameră: unul întins pe sârmă, altul îndoit în patru pe scaun. După trei ore, doar cel întins era uscat.',
      'panza~Un prosop a fost întins, celălalt îndoit~1|vant~Aerul circula prin cameră~1|ceas~După trei ore doar cel întins era uscat~1|soare~Amândouă au stat la umbră~0|apa~Au fost la fel de ude~0',
      'Prosopul întins are o suprafață mare în contact cu aerul|Apa se evaporă de pe toată acea suprafață|Cel îndoit ține apa la mijloc, unde aerul nu ajunge',
      'Cum usuci mai repede?|Întins cât mai desfăcut, în curent de aer;Făcut sul;Pus într-o pungă|0',
      'Evaporarea are loc doar la suprafață. Cu cât e mai mare suprafața expusă la aer, cu atât se usucă mai repede.'],

    ['bucatarie', 'gheata,frigider', 'Cuburile de gheață lipite',
      'Cuburile scoase din congelator s-au lipit între ele într-un bloc. Punga era închisă, iar congelatorul merge la −18 grade.',
      'gheata~Cuburile s-au lipit într-un bloc~1|apa~Pe suprafața lor era o peliculă de apă~1|frigider~Congelatorul e la −18 grade~1|sare~Nu s-a pus sare~0|pahar~Punga era închisă~0',
      'La suprafața cuburilor există mereu un strat subțire de apă|Apa dintre două cuburi a înghețat|Gheața nouă le-a sudat, ca un lipici',
      'Cum le desparți fără să le spargi?|Le ții câteva secunde sub apă rece;Le lovești tare;Le pui înapoi în congelator|0',
      'Gheața are aproape mereu o peliculă subțire de apă la suprafață. Din același motiv aluneci pe ea: patinezi de fapt pe apă.'],

    ['laborator', 'pahar,gheata', 'Paharul plin ochi cu gheață',
      'Rareș a umplut un pahar cu cuburi de gheață și apă, până la buză. Era sigur că, la topire, apa va da pe dinafară. Nu a curs nicio picătură.',
      'gheata~Paharul era plin ochi cu gheață și apă~1|apa~După topire, nivelul a rămas la fel~1|cantar~Gheața plutea, ieșind puțin deasupra~1|soare~Camera e caldă~0|sare~Nu s-a pus sare~0',
      'Gheața plutea, deci împingea la o parte exact atâta apă cât cântărea ea|Topindu-se, a devenit fix acea cantitate de apă|Nivelul din pahar nu s-a schimbat',
      'Ce se întâmplă dacă se topește gheața care plutește pe ocean?|Nivelul aproape nu se schimbă;Crește foarte mult;Scade|0',
      'Atenție: gheața de pe uscat — Groenlanda, Antarctica — e altă poveste. Aceea adaugă apă nouă și chiar ridică nivelul mării.',
      'Care gheață ridică nivelul mării când se topește?|Cea de pe uscat;Cea care plutește;Niciuna|0'],

    /* ---------- 8. LUMINĂ, UMBRE ȘI SUNET ---------- */
    ['gradina', 'soare,rigla', 'Umbra care se scurtează',
      'Ana a măsurat umbra bățului din oră în oră. Dimineața era de 90 cm, la prânz de 30 cm, iar seara iar lungă. Bățul nu s-a mișcat deloc.',
      'soare~La prânz Soarele e cel mai sus pe cer~1|rigla~La prânz umbra e de trei ori mai scurtă~1|ceas~Măsurătorile s-au făcut din oră în oră~1|nor~Cerul a fost senin~0|vant~Nu a bătut vântul~0',
      'Soarele urcă pe cer până la prânz|Razele lui cad tot mai de sus, aproape vertical|Umbra obiectului devine tot mai scurtă',
      'Când e umbra cea mai lungă?|Dimineața devreme și seara;Exact la prânz;La miezul nopții|0',
      'Umbra e locul în care lumina nu ajunge. Lungimea ei arată sub ce unghi vine lumina — de aceea funcționează ceasul solar.',
      'Ce îți spune lungimea umbrei?|Cât de sus e Soarele pe cer;Cât de cald e afară;În ce zi ești|0'],

    ['laborator', 'pahar,rigla', 'Creionul rupt în pahar',
      'Rareș a pus un creion în paharul cu apă. Privit din lateral, creionul pare rupt exact la nivelul apei. Scos afară, e perfect drept.',
      'pahar~Creionul pare rupt fix la nivelul apei~1|apa~Scos din apă, e perfect drept~1|lupa~Lumina se îndoaie când trece din apă în aer~1|soare~Lumina din cameră e bună~0|oglinda~Nu e nicio oglindă~0',
      'Lumina pleacă de la partea scufundată a creionului|La ieșirea din apă în aer, ea își schimbă direcția|Ochiul crede că lumina a venit drept și vede creionul frânt',
      'Cum se numește îndoirea luminii la trecerea dintr-un mediu în altul?|Refracție;Reflexie;Umbră|0',
      'Lumina merge mai încet prin apă decât prin aer. Când își schimbă viteza, își schimbă și direcția — ca o roată care intră în nisip.',
      'De ce pare bazinul mai puțin adânc decât e?|Din cauza refracției;Din cauza culorii apei;Din cauza aerului|0'],

    ['camera', 'usa,soare', 'Orbirea de la intrare',
      'Ana a stat o oră în soare puternic. Când a intrat în hol, nu a văzut absolut nimic câteva secunde, deși holul nu e chiar întunecat.',
      'soare~A stat o oră în soare puternic~1|usa~A intrat brusc în holul întunecos~1|ceas~După două minute vedea bine~1|bec~Becul din hol era stins~0|pisica~Pisica se descurca perfect~0',
      'La lumină puternică, pupila s-a micșorat foarte mult|În întuneric a avut nevoie de timp ca să se lărgească la loc|Până atunci, prea puțină lumină a ajuns în ochi',
      'Ce ajută ochiul să se adapteze mai repede?|Timp și lumină slabă, fără ecrane puternice;Să te uiți la telefon;Să clipești foarte tare|0',
      'Ochiul e o cameră foto cu diafragmă automată. Adaptarea completă la întuneric poate dura chiar 20 de minute.',
      'De ce folosesc marinarii lumini roșii noaptea?|Ca ochiul să rămână adaptat la întuneric;Ca să fie frumos;Ca să vadă mai colorat|0'],

    ['munte', 'rock,toba', 'Ecoul din tunel',
      'Rareș a strigat o singură dată în tunelul lung. A auzit strigătul de două ori. În camera lui, oricât ar striga, nu se aude niciun ecou.',
      'rock~Tunelul are pereți tari și netezi~1|toba~A strigat o dată, a auzit de două ori~1|rigla~Peretele din capăt e la 40 de metri~1|vant~Nu bătea vântul~0|ceas~Era dimineață~0',
      'Sunetul a plecat spre peretele îndepărtat|S-a lovit de el și s-a întors|A ajuns la ureche mult mai târziu decât strigătul original',
      'De ce nu auzi ecou într-o cameră mică?|Sunetul se întoarce prea repede ca să-l distingi;Nu se reflectă deloc;E prea încet|0',
      'Ecoul se distinge doar dacă peretele e la peste 17 metri. Mai aproape, sunetul întors se amestecă cu cel original.',
      'Cine folosește ecoul ca să „vadă"?|Liliacul și delfinul;Vulturul;Fluturele|0'],

    ['plaja', 'soare,panza', 'Tricoul negru fierbinte',
      'Două tricouri identice, unul alb și unul negru, au stat o oră la soare pe aceeași bancă. Cel negru avea 48 de grade, cel alb 33.',
      'soare~Amândouă au stat la același soare~1|termometru~Cel negru are 48 de grade, cel alb 33~1|panza~Sunt din același material~1|vant~Aerul a fost liniștit~0|apa~Amândouă erau uscate~0',
      'Culoarea albă trimite înapoi cea mai mare parte din lumină|Culoarea neagră o absoarbe aproape complet|Lumina absorbită se transformă în căldură',
      'Ce porți vara, la soare puternic?|Haine deschise la culoare;Haine negre;Nu contează culoarea|0',
      'Vezi un obiect negru tocmai pentru că nu îți trimite lumina înapoi. Energia rămâne în el și îl încălzește.',
      'De ce sunt casele din țările calde văruite în alb?|Reflectă lumina și rămân răcoroase;E doar o tradiție;Vopseaua albă e mai ieftină|0'],

    ['camera_noapte', 'fereastra,bec', 'Fața din geam',
      'Seara, Ana s-a apropiat de fereastră ca să se uite în curte. În loc de curte, s-a văzut pe ea, ca într-o oglindă. Ziua, același geam e perfect transparent.',
      'bec~Lumina din cameră e aprinsă~1|luna~Afară e întuneric complet~1|fereastra~Ziua nu se întâmplă asta~1|oglinda~Nu e nicio oglindă în cameră~0|pisica~Pisica se uită și ea~0',
      'Geamul reflectă mereu o mică parte din lumina care cade pe el|Ziua, lumina puternică de afară acoperă complet reflexia|Noaptea, afară e întuneric, așa că reflexia devine imaginea cea mai puternică',
      'Cum vezi mai bine afară, noaptea?|Stingi lumina din cameră;Aprinzi mai multe becuri;Speli bine geamul|0',
      'Sticla e și fereastră, și oglindă slabă, în același timp. Care „câștigă" depinde doar de partea în care e mai multă lumină.',
      'De ce par geamurile fumurii oglindă pe dinafară?|Afară e mult mai multă lumină decât înăuntru;Sunt făcute din metal;Sunt vopsite pe dinafară|0'],

    ['camera', 'difuzor,usa', 'Muzica de la vecini',
      'Prin peretele gros se aude doar „bum-bum-bum". Vocile și chitara nu se disting deloc, deși în camera vecină muzica sună limpede.',
      'difuzor~Se aud doar sunetele joase, ritmul~1|usa~Peretele dintre camere e gros~1|toba~Vocile nu se înțeleg deloc~1|ceas~Este ora 21~0|fereastra~Geamul e închis~0',
      'Sunetele înalte au unde scurte, oprite ușor de perete|Sunetele joase au unde lungi și fac chiar peretele să vibreze|Prin perete trece mai ales basul',
      'Ce oprește cel mai bine basul?|Masa mare și materialele grele;O perdea subțire;Un covoraș mic|0',
      'De aceea, de departe, dintr-o petrecere auzi doar boxa de bas. Sunetele înalte se pierd primele pe drum.',
      'Ce sunete trec cel mai ușor prin ziduri?|Cele joase;Cele înalte;Toate la fel|0'],

    ['spatiu', 'stea,luna', 'Steaua care clipește',
      'Ana a observat că stelele licăresc, dar Luna și un punct luminos foarte strălucitor — o planetă — stau liniștite. Cerul e perfect senin.',
      'stea~Stelele licăresc, planetele aproape deloc~1|vant~Aerul de sus e mereu în mișcare~1|termometru~Straturile de aer au temperaturi diferite~1|luna~Luna nu clipește deloc~1|nor~Cerul e senin~0',
      'Lumina stelei traversează straturi de aer în mișcare|Fiecare strat îi îndoaie raza puțin, mereu altfel|Lumina ajunge la ochi când mai tare, când mai slab: pare că licărește',
      'De ce nu clipesc la fel și planetele?|Se văd ca discuri mici, nu ca puncte;Sunt mai aproape de Soare;Sunt mai luminoase|0',
      'De aceea telescoapele mari se construiesc pe munți înalți sau se trimit în spațiu: acolo aerul deranjează cel mai puțin.',
      'Unde vezi cel mai clar stelele?|Pe un munte înalt, departe de orașe;În centrul orașului;Într-o vale cu ceață|0'],

    ['laborator', 'balon,prisma', 'Culorile bulelor de săpun',
      'Bula de săpun are inele colorate care se mișcă și se schimbă. Cu câteva secunde înainte să se spargă, culorile devin foarte largi, apoi apare o pată neagră.',
      'apa~Pelicula de săpun e foarte subțire~1|soare~Culorile se schimbă când bula se mișcă~1|lupa~Culorile apar sub formă de inele~1|prisma~Nu e nicio prismă în cameră~0|vant~Aerul e liniștit~0',
      'Lumina se reflectă și de fața din față, și de cea din spate a peliculei|Cele două raze reflectate se suprapun|Unele culori se întăresc, altele se sting: apar irizațiile',
      'De ce se schimbă culorile bulei în timp?|Pelicula devine tot mai subțire;Se murdărește;Se încălzește|0',
      'Aceleași culori apar într-o pată de ulei pe asfalt ud: tot un strat foarte subțire, tot aceeași poveste a luminii.',
      'Ce vezi într-o pată de benzină pe apă?|Irizații, ca la bule;Doar negru;Doar alb|0'],

    ['camera_noapte', 'lampa,rigla', 'Cercul lanternei',
      'Ana ține lanterna la un metru de perete: cercul e mic și foarte luminos. La trei metri, cercul e uriaș, dar lumina abia se mai vede.',
      'lampa~Cu cât e mai departe, cercul e mai mare~1|rigla~La 1 m cercul e mic, la 3 m e uriaș~1|bec~Lumina pare mult mai slabă de departe~1|vant~Vântul nu contează~0|ceas~Era seara~0',
      'Lumina pleacă din lanternă sub forma unui con|Cu cât merge mai departe, conul se lărgește|Aceeași cantitate de lumină se împrăștie pe o suprafață mai mare, deci pare mai slabă',
      'Cum obții un punct luminos mai puternic?|Apropii lanterna de perete;O depărtezi mai mult;O înclini|0',
      'De aceea o lumină îndepărtată pare slabă: nu s-a „consumat", ci s-a împrăștiat. La distanță dublă, de patru ori mai slabă.',
      'De două ori mai departe înseamnă…|De patru ori mai slabă lumina;De două ori mai slabă;Exact la fel|0'],

    /* ---------- 9. FORȚE ȘI MIȘCARE ---------- */
    ['strada', 'bicicleta,roata', 'Bicicleta grea de pedalat',
      'Drumul e drept și neted, nu bate vântul, lanțul e uns — dar Rareș pedalează de două ori mai greu decât săptămâna trecută.',
      'bicicleta~Roțile se apasă ușor cu degetul~1|rigla~Cauciucul e turtit acolo unde atinge drumul~1|masinuta~Drumul e drept și neted~1|vant~Nu bate vântul~0|roata~Lanțul e uns~0',
      'Presiunea din anvelope a scăzut în timp|Cauciucul se turtește și atinge drumul pe o suprafață mare|Frecarea crește și pedalezi mult mai greu',
      'Ce faci?|Umfli anvelopele la presiunea scrisă pe ele;Pedalezi mai tare;Slăbești frânele|0',
      'O anvelopă moale se deformează la fiecare rotație, iar deformarea consumă energie. Tu ești motorul care plătește.',
      'De ce merg mai ușor roțile bine umflate?|Se deformează mult mai puțin;Sunt mai grele;Sunt mai late|0'],

    ['strada', 'masinuta,carte', 'Cartea de pe bord',
      'Mașina mergea liniștit, cu o carte pe bord. Când șoferul a frânat brusc la semafor, cartea a zburat înainte și a căzut jos.',
      'masinuta~Mașina a frânat brusc~1|carte~Cartea a alunecat înainte, nu înapoi~1|rigla~Bordul e neted, aproape fără frecare~1|vant~Geamurile erau închise~0|ceas~Mergeau de zece minute~0',
      'Cartea se mișca odată cu mașina, cu aceeași viteză|Mașina a frânat, dar nimic nu a frânat și cartea|Ea a continuat înainte până a căzut',
      'Cum se numește tendința de a-și păstra mișcarea?|Inerție;Gravitație;Frecare|0',
      'De aceea centura de siguranță e obligatorie: la frânare, corpul tău vrea să continue drumul, exact ca acea carte.',
      'De ce te apleci înainte când autobuzul frânează?|Corpul tău păstrează viteza;Ești împins de scaun;Din cauza vântului|0'],

    ['terenjoaca', 'minge,planta', 'Mingea oprită de iarbă',
      'Lovită la fel de tare, mingea a mers 20 de metri pe asfalt și doar 6 metri pe gazon. Nu bate vântul, iar terenul e plat în ambele cazuri.',
      'minge~Pe asfalt 20 m, pe iarbă doar 6 m~1|planta~Firele de iarbă o freacă și o încetinesc~1|rigla~A fost lovită la fel de tare~1|vant~Nu era vânt~0|soare~Era senin~0',
      'Mingea a pornit cu aceeași energie în ambele cazuri|Pe iarbă, frecarea este mult mai mare|Energia s-a consumat mai repede și mingea s-a oprit mai devreme',
      'Pe ce suprafață merge mingea cel mai departe?|Pe gheață;Pe iarbă;Pe nisip|0',
      'Frecarea transformă mișcarea în căldură. Cu cât suprafața e mai aspră, cu atât mișcarea se pierde mai repede.',
      'Ce ar face o minge într-un loc fără frecare și fără aer?|Ar merge la nesfârșit;S-ar opri repede;Ar cădea imediat|0'],

    ['terenjoaca', 'leagan,vant', 'Leagănul care se oprește singur',
      'Ana s-a dat în leagăn și apoi a stat nemișcată. Balansul s-a făcut tot mai mic și, după două minute, leagănul s-a oprit complet.',
      'leagan~Se oprește singur după două minute~1|vant~Aerul îl frânează la fiecare balans~1|sfoara~Lanțurile se freacă în cârligele de sus~1|greutate~Copilul stă complet nemișcat~1|soare~E după-amiază~0',
      'La fiecare balans, aerul și frecarea din cârlige iau puțină energie|Balansul devine tot mai mic|În final, leagănul se oprește',
      'Cum ții leagănul în mișcare?|Împingi ritmic, la momentul potrivit;Împingi tot timpul, oricând;Stai perfect nemișcat|0',
      'Împingerea la momentul potrivit se numește rezonanță: împingeri mici, dar la timp, produc balansuri foarte mari.',
      'Cum îl faci să meargă cel mai sus?|Împingi exact când începe să plece de la tine;Împingi la întâmplare;Îl tragi în jos|0'],

    ['bucatarie', 'pahar,masa', 'Paharul care alunecă singur',
      'Pe masa de sticlă s-a vărsat puțină apă. Paharul pus deasupra a alunecat singur câțiva centimetri, până la marginea mesei.',
      'apa~Pe masă era o peliculă de apă~1|pahar~Fundul paharului e perfect neted~1|masa~Masa e din sticlă, foarte netedă~1|pisica~Pisica nu a fost în bucătărie~0|ceas~Era ora cinei~0',
      'Apa a format o peliculă între pahar și masă|Cele două suprafețe nu s-au mai atins direct|Frecarea a scăzut mult și paharul a alunecat',
      'Ce oprește alunecarea?|Un suport de plută sau un șervet;Mai multă apă;O masă și mai netedă|0',
      'Din același motiv derapează mașinile pe carosabil ud: un film subțire de apă desparte cauciucul de asfalt.',
      'De ce e periculos drumul la prima ploaie?|Apa ridică praful și uleiul și alunecă;Pentru că e mai rece;Pentru că se vede mai bine|0'],

    ['scoala', 'cutie,carte', 'Ghiozdanul care se răstoarnă',
      'Ghiozdanul stă drept când e gol. Plin, cu manualele grele puse în buzunarul de sus, se răstoarnă imediat ce îl lași jos.',
      'greutate~Cărțile grele au fost puse sus~1|cutie~Stă drept doar când e gol~1|rigla~Baza lui e îngustă~1|apa~Nu e ud~0|ceas~Era dimineață~0',
      'Greutatea a fost pusă în partea de sus|Centrul de greutate a urcat foarte mult|La cea mai mică înclinare, greutatea a ieșit din bază și ghiozdanul s-a răsturnat',
      'Unde pui cărțile grele în ghiozdan?|Jos și lipite de spate;Sus, în capac;În buzunarul din față|0',
      'Regula e aceeași pentru ghiozdan, camion și turn de cuburi: greutatea cât mai jos și cât mai aproape de mijloc.',
      'De ce nu se răstoarnă o mașină de curse?|E foarte joasă și lată;E ușoară;E colorată|0'],

    ['munte', 'gheata,rock', 'Sania pe zăpada bătătorită',
      'Pe poteca bătătorită, sania zboară. La doi metri distanță, pe zăpada proaspătă și pufoasă, aceeași sanie abia se târăște.',
      'gheata~Pe poteca bătătorită sania alunecă ușor~1|rigla~Pe zăpada afânată sania se afundă~1|greutate~Sania și copilul cântăresc la fel~1|vant~Nu bate vântul~0|soare~E înnorat~0',
      'Pe zăpada afânată, sania se afundă și împinge zăpadă în față|Acest lucru consumă multă energie|Pe zăpada tare, tălpile alunecă pe o peliculă subțire de apă, cu rezistență mică',
      'Unde alunecă sania cel mai bine?|Pe zăpadă tare, bătătorită;Pe zăpadă proaspătă și pufoasă;Pe iarbă|0',
      'Presiunea tălpii topește un strat microscopic de apă. Pe el aluneci, exact ca patinatorii pe gheață.',
      'De ce alunecă patinele pe gheață?|Se formează un strat subțire de apă;Gheața e unsuroasă;Lama e caldă|0'],

    ['camera', 'carte,vant', 'Hârtia mototolită cade prima',
      'Două foi identice, una întinsă și una făcută ghemotoc, au fost lăsate să cadă de la aceeași înălțime. Ghemotocul a ajuns jos primul, deși cântăresc exact la fel.',
      'carte~Două foi identice, una mototolită~1|ceas~Ghemotocul a ajuns jos primul~1|vant~Aerul din cameră e liniștit~1|cantar~Cântăresc exact la fel~1|soare~Lumina nu contează~0',
      'Foaia întinsă are o suprafață mare|Aerul o frânează puternic pe tot drumul|Ghemotocul, cu suprafață mică, întâmpină mult mai puțină rezistență',
      'Ce s-ar întâmpla fără aer?|Ar cădea amândouă exact la fel;Tot ghemul ar ajunge primul;Tot foaia ar ajunge prima|0',
      'Pe Lună, unde nu există aer, un ciocan și o pană cad la fel. Astronauții au făcut chiar acest experiment, în 1971.',
      'Ce frânează o pană care cade?|Aerul;Gravitația;Greutatea ei|0'],

    ['camera', 'usa,rigla', 'Ușa greu de închis',
      'Împinsă de mâner, ușa se închide cu un deget. Împinsă lângă balamale, aproape că nu se mișcă, deși e aceeași ușă și aceeași forță.',
      'usa~Împinsă lângă balama, abia se mișcă~1|rigla~Împinsă la marginea opusă, se închide ușor~1|greutate~E aceeași ușă, aceeași forță~1|apa~Ușa nu e umflată~0|ceas~Era seara~0',
      'Ușa se rotește în jurul balamalelor|Cu cât apeși mai departe de balama, cu atât brațul pârghiei e mai lung|Cu braț lung, aceeași forță are efect mult mai mare',
      'Unde se pune mânerul ca să deschizi ușor?|Cât mai departe de balamale;Chiar lângă balamale;Exact la mijloc|0',
      'Ușa e o pârghie. De aceea mânerul e mereu în partea opusă balamalelor — nu din obișnuință, ci din fizică.',
      'De ce are cheia franceză mâner lung?|Ca să strângi cu forță mai mare;Ca să fie mai grea;Ca să ajungi mai departe|0'],

    ['bucatarie', 'masa,pahar', 'Fața de masă trasă brusc',
      'Trasă foarte repede, fața de masă a ieșit de sub pahare și acestea au rămas pe loc. Trasă încet, a luat toate paharele cu ea.',
      'masa~Trasă brusc, paharele au rămas pe loc~1|ceas~Trasă încet, paharele au căzut~1|rigla~Fața de masă e netedă, fără tiv gros~1|apa~Paharele erau goale~0|pisica~Pisica privea de pe scaun~0',
      'Obiectele tind să rămână în repaus, din inerție|La o smucitură scurtă, frecarea acționează prea puțin timp ca să le pornească|Trasă încet, frecarea are timp destul să le tragă și pe ele',
      'De ce reușește trucul doar dacă tragi foarte repede?|Frecarea are prea puțin timp să acționeze;Fața de masă devine alunecoasă;Paharele se lipesc de masă|0',
      'Inerția plus timpul foarte scurt fac trucul. Cu pahare grele merge chiar mai bine: sunt și mai greu de pus în mișcare.',
      'Cu ce pahare iese trucul mai sigur?|Cu pahare grele;Cu pahare ușoare de plastic;Cu pahare de hârtie|0'],

    /* ---------- 10. ENERGIE ȘI ELECTRICITATE ---------- */
    ['atelier', 'lampa,baterie', 'Lanterna care nu luminează',
      'Bateriile sunt noi, becul e întreg, butonul face clic. Lanterna tot nu se aprinde. Pe arcurile din capăt sunt urme verzui.',
      'fir~Contactele au urme verzui~1|baterie~Bateriile sunt noi~1|bec~Sârmulița becului nu e ruptă~1|intrerupator~Butonul face clic~0|soare~Era ziuă~0',
      'Pe contacte s-a format un strat de coroziune|Stratul nu lasă curentul să treacă|Circuitul rămâne întrerupt, deși toate piesele sunt bune',
      'Ce încerci prima dată?|Cureți contactele cu o cârpă uscată;Cumperi altă lanternă;Pui bateriile invers|0',
      'Un circuit e ca un drum: dacă lipsește un singur metru de asfalt, mașina nu ajunge, oricât de bun ar fi restul drumului.',
      'De ce curg bateriile vechi?|Substanțele dinăuntru corodează învelișul;Pentru că se încălzesc;Pentru că sunt prea pline|0'],

    ['munte', 'telefon,gheata', 'Telefonul descărcat pe ger',
      'Telefonul avea 40% și a stat o oră în buzunarul exterior, la −8 grade, fără să fie folosit. Când l-a scos, arăta 5% și s-a stins.',
      'gheata~Afară sunt −8 grade~1|telefon~A stat în buzunarul exterior~1|baterie~A sărit de la 40% la 5%~1|ceas~Nu a fost folosit deloc~1|fir~Nu a fost la încărcat~0',
      'Frigul încetinește reacțiile chimice din baterie|Bateria nu mai poate livra curent la fel de ușor|Telefonul crede că e goală și se oprește',
      'Ce faci cu telefonul pe ger?|Îl ții într-un buzunar interior, la cald;Îl ții tot timpul în mână;Îl lași afară, în rucsac|0',
      'De multe ori energia e încă acolo. La cald, procentul „revine" — pentru că bateria poate din nou să o livreze.',
      'Unde ține bateria cel mai bine?|La temperatura camerei;La ger;În soare puternic|0'],

    ['camera', 'fir,telefon', 'Firul cald al încărcătorului',
      'În timpul încărcării rapide, firul încărcătorului e călduț pe toată lungimea, iar adaptorul din priză e cald.',
      'fir~Firul e subțire și strâns colac~1|telefon~Se încarcă în modul rapid~1|termometru~Firul e călduț, nu fierbinte~1|apa~Nu e ud nimic~0|ceas~Se încarcă de o oră~0',
      'Prin fir trece curent electric|Firul are o mică rezistență|O parte din energie se transformă în căldură chiar în fir',
      'Când trebuie să te îngrijorezi?|Când firul e fierbinte sau are izolația crăpată;Când e doar călduț;Când e nou|0',
      'Efectul se numește Joule. Aceeași căldură e folosită intenționat în prăjitorul de pâine și în uscătorul de păr.',
      'În ce transformă un uscător curentul?|În căldură și mișcarea aerului;Doar în lumină;Doar în sunet|0'],

    ['camera', 'bec,baterie', 'Becul care frige',
      'Becul vechi din veioză frige după cinci minute. Becul LED din lampa de birou luminează la fel de tare, dar rămâne rece și consumă de șase ori mai puțin.',
      'bec~Becul vechi frige după cinci minute~1|bec~Becul LED rămâne rece~1|baterie~Cel vechi consumă de șase ori mai mult~1|intrerupator~Amândouă luminează la fel de tare~1|soare~Lumina de afară nu contează~0',
      'Becul cu filament încălzește o sârmă până devine incandescentă|Cea mai mare parte din energie se pierde ca și căldură|Doar o mică parte devine lumină',
      'De ce consumă LED-ul mai puțin?|Transformă mult mai multă energie direct în lumină;Pentru că e mai mic;Pentru că e mai ieftin|0',
      'Becul clasic e, de fapt, o sobiță care luminează pe lângă. LED-ul face lumină aproape fără căldură.',
      'Unde se duce cea mai mare parte din energia unui bec clasic?|În căldură;Toată în lumină;În sunet|0'],

    ['camera', 'usa,panza', 'Șocul de la clanță',
      'Ana a traversat covorul în papuci de cauciuc și a atins clanța metalică. A simțit o înțepătură și a auzit un pocnet mic. Se întâmplă doar iarna.',
      'panza~A mers pe covor, în papuci de cauciuc~1|gheata~Aerul din casă e uscat, e iarnă~1|usa~Clanța e din metal~1|apa~Nu e nimic ud~0|bec~Lumina era aprinsă~0',
      'Frecarea de covor i-a încărcat corpul cu sarcini electrice|Aerul uscat nu a lăsat sarcinile să se scurgă treptat|La atingerea metalului au trecut toate deodată: scânteie',
      'Cum eviți șocul?|Atingi întâi metalul cu o cheie ținută în mână;Alergi pe covor;Porți papuci noi|0',
      'Scânteia are mii de volți, dar foarte puțină energie. Înțeapă neplăcut, însă nu e periculoasă.',
      'Când apar mai des șocurile statice?|Iarna, cu aer uscat;Vara, cu aer umed;Imediat după ploaie|0'],

    ['bucatarie', 'intrerupator,foc', 'Siguranța sărită',
      'Mama a pornit cuptorul, apoi aeroterma și fierul de călcat. În câteva secunde s-a stins lumina în toată casa, dar la vecini era curent.',
      'fir~S-au pornit trei aparate mari deodată~1|intrerupator~Siguranța a sărit imediat~1|bec~Restul casei a rămas fără curent~1|apa~Nu s-a vărsat apă~0|ceas~Era ora prânzului~0',
      'Toate aparatele mari au tras curent în același timp|Curentul total a depășit limita circuitului|Siguranța a întrerupt circuitul înainte ca firele să se încingă',
      'Ce faci?|Oprești câteva aparate, apoi ridici siguranța;Ridici siguranța și pornești tot la loc;Legi firele direct|0',
      'Siguranța nu e o pacoste: e paznicul care sacrifică lumina ca să nu ia foc peretele.',
      'De ce sare siguranța?|Ca să protejeze instalația de supraîncălzire;Ca să economisească curent;Din cauza becurilor|0'],

    ['camera', 'ventilator,termometru', 'Ventilatorul care nu răcește',
      'Rareș a lăsat ventilatorul pornit două ore, cu ușa închisă. Termometrul arată tot 29 de grade, dar în bătaia lui se simte clar mai bine.',
      'termometru~Termometrul arată tot 29 de grade~1|ventilator~În bătaia lui te simți răcorit~1|apa~Pielea e ușor umedă de transpirație~1|usa~Ușa e închisă~0|soare~Perdelele sunt trase~0',
      'Ventilatorul mișcă aerul, dar nu îl răcește|Aerul în mișcare grăbește evaporarea transpirației de pe piele|Evaporarea îți ia căldură și te simți răcorit',
      'Are rost ventilatorul într-o cameră goală?|Nu, nu răcește aerul;Da, răcește camera;Da, dacă stă pornit mult|0',
      'Ventilatorul răcorește oameni, nu camere. Motorul lui chiar încălzește aerul, foarte puțin.',
      'Ce te răcorește, de fapt?|Evaporarea transpirației;Aerul rece produs de ventilator;Zgomotul lui|0'],

    ['bucatarie', 'frigider,soare', 'Frigiderul care pornește des',
      'Vara, motorul frigiderului pornește la fiecare zece minute. Iarna pornea mult mai rar. Becul dinăuntru se stinge corect când închizi ușa.',
      'soare~În bucătărie sunt 30 de grade~1|frigider~Motorul pornește la zece minute~1|usa~Ușa e deschisă des, e vacanță~1|gheata~Iarna pornea mult mai rar~1|bec~Becul dinăuntru funcționează~0',
      'Diferența dintre interiorul rece și bucătăria caldă e foarte mare|Căldura intră mai repede prin pereți și pe ușa deschisă|Motorul pornește mai des ca să scoată căldura afară',
      'Cum consumă mai puțin?|Ții ușa închisă și lași spațiu de aerisire în spate;Îl muți lângă aragaz;Îl dai pe treapta maximă|0',
      'Frigiderul nu „face frig": mută căldura din interior în cameră. De aceea, în spatele lui e mereu cald.',
      'Unde ajunge căldura scoasă din frigider?|În cameră, prin grătarul din spate;Dispare pur și simplu;În congelator|0'],

    ['gradina', 'panou_solar,nor', 'Panoul solar leneș',
      'Lampa solară din grădină lumina 6 ore în iulie. În noiembrie ține doar o oră, deși e același panou și aceeași baterie.',
      'nor~A fost înnorat aproape toată luna~1|panou_solar~Panoul e acoperit de un strat de praf~1|ceas~Zilele sunt scurte, e noiembrie~1|baterie~Bateria s-a încărcat doar 20%~1|fir~Firele sunt bune~0',
      'Norii, praful și zilele scurte au redus lumina primită|Panoul a produs mult mai puțin curent|Bateria s-a încărcat doar pe sfert',
      'Ce poți face imediat?|Ștergi praful de pe panou;Îl întorci spre nord;Îl acoperi cu o folie|0',
      'Panoul transformă lumina în curent. Fără lumină nu are din ce. Curățenia și unghiul contează enorm.',
      'Spre ce direcție se orientează panourile solare, la noi?|Spre sud;Spre nord;Spre vest|0'],

    ['camera', 'robot,baterie', 'Bateriile golite peste noapte',
      'Rareș a pus baterii noi în robot marți. Vineri erau goale, deși nu s-a jucat aproape deloc. Robotul a stat în cutie, cu un led mic aprins.',
      'bec~Un led mic a rămas aprins tot timpul~1|intrerupator~Butonul a rămas pe „pornit"~1|ceas~Bateriile erau noi de două zile~1|cutie~Robotul a stat închis în cutie~1|apa~Nu s-a udat~0',
      'Jucăria a rămas pornită după joacă|Ledul și circuitul au consumat curent fără oprire|În 40 de ore bateriile s-au golit, deși nimeni nu s-a jucat',
      'Ce reguli ajută?|Oprești jucăria după joacă și scoți bateriile la depozitare;Cumperi baterii mai mari;Le ții în frigider|0',
      'Un consum mic, dar continuu, golește o baterie la fel de sigur ca unul mare și scurt. Se numește consum în așteptare.',
      'Ce consumă mai mult într-o zi?|Un led mic aprins 24 de ore;Aceeași jucărie pornită 10 minute;Niciunul|0']
  ]
};
